### PR TITLE
Add `try`-`except` blocks around `F.symlink()` calls that fail on Windows

### PR DESCRIPTION
**Pull request by pwintz**
I added try-except blocks around the code that causes failures while cloning. Eventually, all of the errors should be corrected, of course, but until then, this will make testing things easier.

### CODE REVIEW

**Comment by langfield** [comment]
I think this is a great idea! First, though, I would like to slightly refactor `write_decks()`. It is already a monstrous function.

https://github.com/langfield/ki/blob/a44408e4d168dc65967ea944bc3f068e61c113ab/ki/__init__.py#L1206-L1210

https://github.com/langfield/ki/blob/a44408e4d168dc65967ea944bc3f068e61c113ab/ki/__init__.py#L1302-L1310

https://github.com/langfield/ki/blob/a44408e4d168dc65967ea944bc3f068e61c113ab/ki/__init__.py#L1322-L1326

Specifically, the blocks inside each of these loops should almost certainly be moved out into three separate functions:

1. A function that handles a single `DeckTreeNode`, and returns stuff to be added to `written_cids: Set[int]` and `written_notes: Dict[int, WrittenNoteFile]`.
2. ...
3. ...

**Comment by langfield** [comment]
My plan is to merge this into its own feature branch, maybe `ki@write-decks-try-except-blocks`, and then do the refactoring on top of your commit(s).

**Comment by langfield** [comment]
@pwintz Do you think you could paste examples of all the raised `Exception`s you've run into within these blocks? I would prefer to pinpoint the problematic lines a bit more closely, rather than `try`-`except` everything.

In general, I worry about merging code that is intended to be used for debugging. It has a tendency to stay there indefinitely.

**Comment by pwintz** [comment]
I've updated the PR to have narrower try blocks (and improved the log output to include the stack trace)

**Comment by langfield** [comment]
@pwintz Now **that** is beautiful. Thanks so much! :100:

**Pull request merged**
