### PR TITLE
Reduce `BATCH_SIZE` constant used to determine how many files to `tidy` at once

### LINKED ISSUE #16: WinError 206: The filename or extension is too long
When I tried to run `ki clone`, it printed the following error.

```
$ ki clone /c/Users/pwintz/AppData/Roaming/Anki2/Paul/collection.anki2
Cloning.
Found .anki2 file at 'C:\Users\pwintz\AppData\Roaming\Anki2\Paul\collection.anki2'
Computed md5sum: 0d120bb433ba3bf106c0696cbca101d3
Cloning into 'C:\Users\pwintz\flashcards\collection'...
Notes: 100%|##############################| 3594/3594 [00:02<00:00, 1694.55it/s]
HTML:   0%|                                               | 0/7 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\Scripts\ki-script.py", line 33, in <module>
    sys.exit(load_entry_point('ki==0.0.1a0', 'console_scripts', 'ki')())
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\__init__.py", line 1598, in clone
    _, _ = _clone(col_file, targetdir, msg="Initial commit", silent=False)
  File "<@beartype(ki._clone) at 0x1a00b224040>", line 86, in _clone
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\__init__.py", line 1656, in _clone
    write_repository(col_file, targetdir, leaves, directories.dirs[MEDIA], silent)
  File "<@beartype(ki.write_repository) at 0x1a00b213ee0>", line 106, in write_repository
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\__init__.py", line 1056, in write_repository
    tidy_html_recursively(root, silent)
  File "<@beartype(ki.tidy_html_recursively) at 0x1a00b206a60>", line 49, in tidy_html_recursively
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\__init__.py", line 1400, in tidy_html_recursively
    raise err
  File "C:\Users\pwintz\AppData\Roaming\Python\Python39\site-packages\ki\__init__.py", line 1398, in tidy_html_recursively
    subprocess.run(command, check=False, capture_output=True)
  File "c:\program files\python39\lib\subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\program files\python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\program files\python39\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 206] The filename or extension is too long
```

### PR DESCRIPTION
**Pull request by langfield**
Fixes #16.

### CODE REVIEW

**Comment by langfield** [comment]
@pwintz This is just a one-line change, setting the `BATCH_SIZE` to `50`. Let me know which of the options mentioned in https://github.com/langfield/ki/issues/16#issuecomment-1210547391 you prefer, and if you think I should just stick with `50`, I can merge this in and delete the feature branch I made the other day.

**Comment by pwintz** [comment]
Ah, I posted just after you did, on #16. Cloning works on my machine when BATCH_SIZE is up to 413, so I'd say maybe use BATCH_SIZE=400?

**Comment by pwintz** [comment]
Do you have a sense of whether this would be machine-dependent? Would a machine with, e.g., less RAM, need a lower batch size?

**Comment by langfield** [comment]
> Ah, I posted just after you did, on #16. Cloning works on my machine when BATCH_SIZE is up to 413, so I'd say maybe use BATCH_SIZE=400?

Fantastic!

**Comment by langfield** [comment]
> Do you have a sense of whether this would be machine-dependent? Would a machine with, e.g., less RAM, need a lower batch size?

No, I don't know. :disappointed:  I do think this is possibly the case. I've gone with `300` to be safe. We currently have exactly 2 data points, the CI machine and yours. How much RAM have you got?

**Comment by langfield** [comment]
One option is to write a function that catches the raised exception and automatically lowers the batch size, but I don't want to add complexity like that unless we get, say, at least two more people with the same issue going forward.

**Comment by langfield** [comment]
As I mentioned in https://github.com/langfield/ki/issues/16#issuecomment-1207379027, it could be hitting the limit on the number of parallel processes running. Not sure if that's a pure function of `RAM` on windows, or if it's just a hard limit that's lower than that on POSIX. :woman_shrugging:

**Comment by pwintz** [comment]
> > Do you have a sense of whether this would be machine-dependent? Would a machine with, e.g., less RAM, need a lower batch size?
> 
> No, I don't know. 😞 I do think this is possibly the case. I've gone with `300` to be safe. We currently have exactly 2 data points, the CI machine and yours. How much RAM have you got?

I have 16GB.

**Pull request merged**
